=== undersea/Special_Topic/src/papers/papers.dtd
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT points (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT paper (code, name, points, offering+, description?, prerequisite?,
          corequisite?, restriction?)>
<!ATTLIST paper code ID #REQUIRED>
<!ELEMENT offering (mode?, campus, semester)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT campus (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT prerequisite ((code|and|or|oneof|any|points)+,exception?)>
<!ELEMENT restriction (code+)>
<!ELEMENT corequisite ((code|or|oneof)+,exception?)>
<!ELEMENT and ((code|any|or), (code|any|or)+)>
<!ELEMENT or (((code|any|and), (code|any|and)+)?)>
<!ATTLIST or
          required CDATA #IMPLIED
          type CDATA #FIXED "subject">
<!ELEMENT oneof ((code|any), (code|any)+)>
<!ELEMENT any (level+)>
<!ELEMENT exception (#PCDATA)>
<!ELEMENT papers (paper+)>

=== undersea/Special_Topic/src/papers/papers.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE papers SYSTEM "papers.dtd">
<papers>
  <paper code="117.152">
    <name>Animals and Agriculture</name>
    <points>15</points>
  </paper>
  <paper code="189.151">
    <name>Soil Properties and Processes</name>
    <points>15</points>
    <restriction>
      <code>189.142</code>
    </restriction>
  </paper>
  <paper code="194.101">
    <name>Essentials of Mammalian Biology</name>
    <points>15</points>
  </paper>
  <paper code="283.101">
    <name>Plants in Agriculture</name>
    <points>15</points>
    <restriction>
      <code>171.102</code>
    </restriction>
  </paper>
  <paper code="117.254">
        <name>Principles of Animal Science and Production</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>194.101</code>
            <code>199.101</code>
            <code>117.152</code>
          </or>
        </prerequisite>
      </paper>
      <paper code="119.258">
        <name>Agricultural Systems</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>117.152</code>
            <code>145.121</code>
          </or>
          <exception>nil for Grad DipRural Studies</exception>
        </prerequisite>
      </paper>
      <paper code="189.251">
        <name>Soil Fertility and Fertilisers</name>
        <points>15</points>
        <prerequisite>
          <code>189.151</code>
        </prerequisite>
      </paper>
      <paper code="189.252">
        <name>Land, Soil and Water</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>189.151</code>
            <code>189.141</code>
            <code>233.101</code>
          </or>
        </prerequisite>
      </paper>
      <paper code="283.201">
        <name>Pasture and Crop Agronomy</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>171.102</code>
            <code>120.101</code>
          </or>
        </prerequisite>
        <restriction>
          <code>171.202</code>
        </restriction>
      </paper>
      <paper code="117.342">
        <name>Animal Nutrition</name>
        <points>5</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper code="117.344">
        <name>Animal Growth and Meat Production</name>
        <points>15</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper code="117.345">
        <name>Genetics for Livestock Improvement</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>117.254</code>
            <code>203.202</code>
          </or>
        </prerequisite>
      </paper>
      <paper code="117.347">
        <name>Reproductive and Lactational Physiology</name>
        <points>15</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper code="117.348">
        <name>Animal Metabolism</name>
        <points>15</points>
        <prerequisite>
          <code>122.102</code>
          <code>194.241</code>
          <or>
            <code>122.233</code>
            <code>151.232</code>
            <code>194.242</code>
          </or>
        </prerequisite>
        <restriction>
          <code>194.346</code>
        </restriction>
        <!--(2001-2005)-->
      </paper>
      <paper code="117.371">
        <name>Animal Production</name>
        <points>15</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper code="117.381">
        <name>Solving Problems in Animal Production</name>
        <points>15</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper code="119.373">
        <name>Integrative Studies</name>
        <points>15</points>
        <prerequisite>
          <points>240</points>
        </prerequisite>
      </paper>
      <paper code="189.362">
        <name>Soil Fertility and the Environment</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>189.251</code>
            <code>189.252</code>
          </or>
        </prerequisite>
      </paper>
      <paper code="189.363">
        <name>Soil Resources and Sustainable Land Use</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>189.251</code>
            <code>189.252</code>
            <code>233.210</code>
            <code>233.310</code>
          </or>
        </prerequisite>
      </paper>
      <paper code="283.301">
        <name>Pasture Production and Practice</name>
        <points>15</points>
        <prerequisite>
          <code>171.202</code>
        </prerequisite>
      </paper>
      <paper code="283.305">
        <name>Seed and Crop Science</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>171.202</code>
            <code>120.101</code>
            <code>171.102</code>
          </or>
          <any>
            <level>200</level>
          </any>
        </prerequisite>
      </paper>
      <paper code="283.311">
        <name>Controlling Weeds</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>120.101</code>
            <code>171.102</code>
          </or>
          <any>
            <level>200</level>
          </any>
        </prerequisite>
      </paper>
      <paper code="285.301">
        <name>Controlling Plant Pests and Diseases</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>171.284</code>
            <code>171.202</code>
          </or>
        </prerequisite>
        <restriction>
          <code>171.384</code>
        </restriction>
      </paper>
      <paper code="159.101">
        <name>Programming Fundamentals</name>
        <points>15</points>
      </paper>
      <paper code="159.102">
        <name>Computer Science Fundamentals</name>
        <points>15</points>
        <prerequisite>
          <code>159.101</code>
        </prerequisite>
      </paper>
      <paper code="159.201">
        <name>Algorithms and Data Structures</name>
        <points>15</points>
        <prerequisite>
          <code>159.101</code>
          <code>159.102</code>
        </prerequisite>
        <restriction>
          <code>159.211</code>
        </restriction>
      </paper>
      <paper code="159.202">
        <name>Declarative Programming</name>
        <points>15</points>
        <prerequisite>
          <code>159.101</code>
          <code>159.102</code>
        </prerequisite>
        <restriction>
          <code>159.211</code>
        </restriction>
      </paper>
      <paper code="159.233">
        <name>Computer Architecture</name>
        <points>15</points>
        <prerequisite>
          <code>159.101</code>
          <code>159.102</code>
        </prerequisite>
        <restriction>
          <code>159.253</code>
        </restriction>
      </paper>
      <paper code="159.234">
        <name>Object-Oriented Programming</name>
        <points>15</points>
        <prerequisite>
          <code>159.101</code>
        </prerequisite>
        <restriction>
          <code>159.211</code>
        </restriction>
      </paper>
      <paper code="159.235">
        <name>Graphical Programming</name>
        <points>15</points>
        <prerequisite>
          <code>159.101</code>
          <code>159.102</code>
        </prerequisite>
      </paper>
      <paper code="159.253">
        <name>Computer Systems</name>
        <points>15</points>
        <prerequisite>
          <code>159.101</code>
          <code>159.102</code>
        </prerequisite>
        <restriction>
          <code>159.233</code>
        </restriction>
      </paper>
      <paper code="159.254">
        <name>Software Engineering A</name>
        <points>15</points>
        <prerequisite>
          <code>159.1xx</code>
        </prerequisite>
        <restriction>
          <code>158.225</code>
        </restriction>
      </paper>
      <paper code="158.359">
        <name>Human-Computer Interaction</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>157.2xx</code>
            <code>158.2xx</code>
            <code>159.2xx</code>
          </or>
        </prerequisite>
        <restriction>
          <code>157.356</code>
          <code>157.359</code>
          <code>159.353</code>
        </restriction>
      </paper>
      <paper code="159.302">
        <name>Artificial Intelligence</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>159.201</code>
            <code>159.202</code>
            <code>159.211</code>
          </or>
        </prerequisite>
        <restriction>
          <code>159.318</code>
        </restriction>
      </paper>
      <paper code="159.331">
        <name>Algorithms and Languages</name>
        <points>15</points>
        <prerequisite>
          <code>159.201</code>
          <code>159.202</code>
        </prerequisite>
        <restriction>
          <code>159.311</code>
        </restriction>
      </paper>
      <paper code="159.333">
        <name>Project Implementation</name>
        <points>15</points>
        <!--P P PD-->
      </paper>
      <paper code="159.334">
        <name>Computer Networks</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>159.201</code>
            <code>159.234</code>
          </or>
        </prerequisite>
        <restriction>
          <code>159.354</code>
        </restriction>
      </paper>
      <paper code="159.335">
        <name>Concurrent Programming and Operating Systems</name>
        <points>15</points>
        <prerequisite>
          <code>159.201</code>
        </prerequisite>
        <restriction>
          <code>159.355</code>
