=== undersea/Special_Topic/src/rules.dtd
<!ELEMENT degree (name, description?, rules, schedule)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT rules (rule+)>
<!ELEMENT rule (limit|atleast|required)>
<!ELEMENT limit (notschedule?, points, level)>
<!ELEMENT notschedule EMPTY>
<!ELEMENT atleast (points, level)>
<!ELEMENT required (code+)>
<!ELEMENT points (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT paper (code, name, points, prerequisite?, corequisite?, restriction?)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT prerequisite ((code|or|oneof|any|points)+,exception?)>
<!ELEMENT restriction (code+)>
<!ELEMENT corequisite ((code|or|oneof)+,exception?)>
<!ELEMENT or ((code|any), (code|any)+)>
<!ELEMENT oneof ((code|any), (code|any)+)>
<!ELEMENT any (level+)>
<!ELEMENT exception (#PCDATA)>
<!ELEMENT schedule (major+)>
<!ELEMENT major (name, paper+, rules?)>

=== undersea/Special_Topic/src/BSc.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE degree SYSTEM "rules.dtd">
<degree>
  <name>BSc</name>
  <rules>
    <rule>
      <limit>
        <points>165</points>
        <level>100</level>
      </limit>
    </rule>
    <rule>
      <atleast>
        <points>75</points>
        <level>300</level>
      </atleast>
    </rule>
    <!--<rule>
      
    </rule>-->
  </rules>
  <schedule>
    <major>
      <name>Agricultural Science</name>
      <paper>
        <code>117.152</code>
        <name>Animals and Agriculture</name>
        <points>15</points>
      </paper>
      <paper>
        <code>189.151</code>
        <name>Soil Properties and Processes</name>
        <points>15</points>
        <restriction>
          <code>189.142</code>
        </restriction>
      </paper>
      <paper>
        <code>194.101</code>
        <name>Essentials of Mammalian Biology</name>
        <points>15</points>
      </paper>
      <paper>
        <code>283.101</code>
        <name>Plants in Agriculture</name>
        <points>15</points>
        <restriction>
          <code>171.102</code>
        </restriction>
      </paper>
      <paper>
        <code>117.254</code>
        <name>Principles of Animal Science and Production</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>194.101</code>
            <code>199.101</code>
            <code>117.152</code>
          </or>
        </prerequisite>
      </paper>
      <paper>
        <code>119.258</code>
        <name>Agricultural Systems</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>117.152</code>
            <code>145.121</code>
          </or>
          <exception>nil for Grad DipRural Studies</exception>
        </prerequisite>
      </paper>
      <paper>
        <code>189.251</code>
        <name>Soil Fertility and Fertilisers</name>
        <points>15</points>
        <prerequisite>
          <code>189.151</code>
        </prerequisite>
      </paper>
      <paper>
        <code>189.252</code>
        <name>Land, Soil and Water</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>189.151</code>
            <code>189.141</code>
            <code>233.101</code>
          </or>
        </prerequisite>
      </paper>
      <paper>
        <code>283.201</code>
        <name>Pasture and Crop Agronomy</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>171.102</code>
            <code>120.101</code>
          </or>
        </prerequisite>
        <restriction>
          <code>171.202</code>
        </restriction>
      </paper>
      <paper>
        <code>117.342</code>
        <name>Animal Nutrition</name>
        <points>5</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper>
        <code>117.344</code>
        <name>Animal Growth and Meat Production</name>
        <points>15</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper>
        <code>117.345</code>
        <name>Genetics for Livestock Improvement</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>117.254</code>
            <code>203.202</code>
          </or>
        </prerequisite>
      </paper>
      <paper>
        <code>117.347</code>
        <name>Reproductive and Lactational Physiology</name>
        <points>15</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper>
        <code>117.348</code>
        <name>Animal Metabolism</name>
        <points>15</points>
        <prerequisite>
          <code>122.102</code>
          <code>194.241</code>
          <or>
            <code>122.233</code>
            <code>151.232</code>
            <code>194.242</code>
          </or>
        </prerequisite>
        <restriction>
          <code>194.346</code>
        </restriction>
        <!--(2001-2005)-->
      </paper>
      <paper>
        <code>117.371</code>
        <name>Animal Production</name>
        <points>15</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper>
        <code>117.381</code>
        <name>Solving Problems in Animal Production</name>
        <points>15</points>
        <prerequisite>
          <code>117.254</code>
        </prerequisite>
      </paper>
      <paper>
        <code>119.373</code>
        <name>Integrative Studies</name>
        <points>15</points>
        <prerequisite>
          <points>240</points>
        </prerequisite>
      </paper>
      <paper>
        <code>189.362</code>
        <name>Soil Fertility and the Environment</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>189.251</code>
            <code>189.252</code>
          </or>
        </prerequisite>
      </paper>
      <paper>
        <code>189.363</code>
        <name>Soil Resources and Sustainable Land Use</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>189.251</code>
            <code>189.252</code>
            <code>233.210</code>
            <code>233.310</code>
          </or>
        </prerequisite>
      </paper>
      <paper>
        <code>283.301</code>
        <name>Pasture Production and Practice</name>
        <points>15</points>
        <prerequisite>
          <code>171.202</code>
        </prerequisite>
      </paper>
      <paper>
        <code>283.305</code>
        <name>Seed and Crop Science</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>171.202</code>
            <code>120.101</code>
            <code>171.102</code>
          </or>
          <any>
            <level>200</level>
          </any>
        </prerequisite>
      </paper>
      <paper>
        <code>283.311</code>
        <name>Controlling Weeds</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>120.101</code>
            <code>171.102</code>
          </or>
          <any>
            <level>200</level>
          </any>
        </prerequisite>
      </paper>
      <paper>
        <code>285.301</code>
        <name>Controlling Plant Pests and Diseases</name>
        <points>15</points>
        <prerequisite>
          <or>
            <code>171.284</code>
            <code>171.202</code>
          </or>
        </prerequisite>
        <restriction>
          <code>171.384</code>
        </restriction>
      </paper>
    </major>
  </schedule>
</degree>
